# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://yoursite.com
title: TeSuple
email: your-email@domain.com
author: Alfredo Quintana
description: > # "Write an awesome description for your new site here. 
  You can edit this line in _config.yml. It will appear in your document 
  head meta (for Google search results) and in your feed.xml site 
  description.
copyright: 'Copyright &copy; 2020 TeSuple3000. All Rights Reserved.'
credits1: 'Teléfono Oficina <a href="tel:+582126938966">212 - 693 8966</a>'
credits2: 'Telefono Celular <a href = "tel:+584129191617">412 - 919 1617</a>'
# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: whatsapp
    url: https://wa.me/584129191617
    icon: whatsapp
  - title: instagram
    url: 
    icon: instagram
  - title: correo
    url: mailto:tesuple3000@gmail.com
    icon: google
